### ISSUE TITLE
Is it safe to use this SDK in a production environment?

### ISSUE THREAD

**Issue by bollus** [clerk/clerk-sdk-java#13]
Hi,

I am considering using this SDK for my production product. I would like to know if it is safe to do so at this point. Are the basic functionalities of this SDK stable and fully developed? Any guidance on this would be greatly appreciated.

Thank you!

**Comment by simplesagar** [comment]
Hi @bollus, thanks for the note ! Yes the SDK is stable and ready for usage. We are keeping the pre release tag (`-beta` suffix) on versions as we gather feedback from early users.
